import { airPodsImg, appleWatchImg, applePencilImg, caboUSBCImg, magicMouseImg, carregadorUSBImg, capaSiliconeImg, smartKeyboardImg } from './constImages';

const produtos = [
    {
      id: 1,
      nome: "AirPods Apple",
      descricao: "Fones de Ouvido",
      valor: 1499.00,
      desconto: 10,
      parcelas: 12,
      quantidade: 0,
      path: airPodsImg,
    },
    {
      id: 2,
      nome: "Capa de Silicone para IPhone 8/7",
      descricao: "cor areia, rosa",
      valor: 299.00,
      desconto: 10,
      parcelas: 12,
      quantidade: 0,
      path: capaSiliconeImg,
    },
    {
      id: 3,
      nome: "Apple Pencil",
      descricao: "",
      valor: 729.00,
      desconto: 10,
      parcelas: 12,
      quantidade: 0,
      path: applePencilImg,
    },
    {
      id: 4,
      nome: "Magic Mouse 2",
      descricao: "Prateado",
      valor: 549.00,
      desconto: 10,
      parcelas: 12,
      quantidade: 0,
      path: magicMouseImg,
    },
    {
      id: 5,
      nome: "Apple Watch",
      descricao: "Caixa prateada de alumínio com pulseira esportiva branca",
      valor: 2899.00,
      desconto: 10,
      parcelas: 12,
      quantidade: 0,
      path: appleWatchImg,
    },
    {
      id: 6,
      nome: "Cabo USB Type-C",
      descricao: "Cabo de lighting para USB (1m)",
      valor: 149.00,
      desconto: 10,
      parcelas: 12,
      quantidade: 0,
      path: caboUSBCImg,
    },
    {
      id: 7,
      nome: "Smart Keyboard para Ipad Pro",
      descricao: "12,9 polegadas, inglês(EUA)",
      valor: 1099.00,
      desconto: 10,
      parcelas: 12,
      quantidade: 0,
      path: smartKeyboardImg,
    },
    {
      id: 8,
      nome: "Carregador USB",
      descricao: "de 5w da Apple",
      valor: 149.00,
      desconto: 10,
      parcelas: 12,
      quantidade: 0,
      path: carregadorUSBImg,
    },
  ];

  export default produtos;