const produtos = [
    {
      nome: "AirPods Apple",
      descricao: "Fones de Ouvido",
      valor: 1499,
      desconto: 10,
      parcelas: 12,
      path: "../../img/air-pods.jpeg",
    },
    {
      nome: "Capa de Silicone para IPhone 8/7",
      descricao: "cor areia, rosa",
      valor: 299,
      desconto: 10,
      parcelas: 12,
      path: "../../img/capa-silicone.jpeg",
    },
    {
      nome: "Apple Pencil",
      descricao: "",
      valor: 729,
      desconto: 10,
      parcelas: 12,
      path: "../../img/apple-pencil.jpeg",
    },
    {
      nome: "Magic Mouse 2",
      descricao: "Prateado",
      valor: 549,
      desconto: 10,
      parcelas: 12,
      path: "../../img/magic-mouse-2.jpeg",
    },
    {
      nome: "Apple Watch",
      descricao: "Caixa prateada de alumínio com pulseira esportiva branca",
      valor: 2899,
      desconto: 10,
      parcelas: 12,
      path: "../../img/apple-watch.jpeg",
    },
    {
      nome: "Cabo USB Type-C",
      descricao: "Cabo de lighting para USB (1m)",
      valor: 149,
      desconto: 10,
      parcelas: 12,
      path: "../../img/cabo-usbc.jpeg",
    },
    {
      nome: "Smart Keyboard para Ipad Pro",
      descricao: "12,9 polegadas, inglês(EUA)",
      valor: 1099,
      desconto: 10,
      parcelas: 12,
      path: "../../img/smart-keyboard.jpeg",
    },
    {
      nome: "Carregador USB",
      descricao: "de 5w da Apple",
      valor: 149,
      desconto: 10,
      parcelas: 12,
      path: "../../img/carregador-usb.jpeg",
    },
  ];

  export default produtos;